/**
 * Bottega
 * KSF Media's orders service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Bottega) {
      root.Bottega = {};
    }
    root.Bottega.BuyingOption = factory(root.Bottega.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The BuyingOption model module.
   * @module model/BuyingOption
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>BuyingOption</code>.
   * @alias module:model/BuyingOption
   * @class
   * @param buyingOptionPackage {String} 
   * @param buyingOptionPeriod {Number} 
   * @param buyingOptionPayAmountCents {Number} 
   */
  var exports = function(buyingOptionPackage, buyingOptionPeriod, buyingOptionPayAmountCents) {
    var _this = this;

    _this['buyingOptionPackage'] = buyingOptionPackage;
    _this['buyingOptionPeriod'] = buyingOptionPeriod;
    _this['buyingOptionPayAmountCents'] = buyingOptionPayAmountCents;
  };

  /**
   * Constructs a <code>BuyingOption</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BuyingOption} obj Optional instance to populate.
   * @return {module:model/BuyingOption} The populated <code>BuyingOption</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('buyingOptionPackage')) {
        obj['buyingOptionPackage'] = ApiClient.convertToType(data['buyingOptionPackage'], 'String');
      }
      if (data.hasOwnProperty('buyingOptionPeriod')) {
        obj['buyingOptionPeriod'] = ApiClient.convertToType(data['buyingOptionPeriod'], 'Number');
      }
      if (data.hasOwnProperty('buyingOptionPayAmountCents')) {
        obj['buyingOptionPayAmountCents'] = ApiClient.convertToType(data['buyingOptionPayAmountCents'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {String} buyingOptionPackage
   */
  exports.prototype['buyingOptionPackage'] = undefined;
  /**
   * @member {Number} buyingOptionPeriod
   */
  exports.prototype['buyingOptionPeriod'] = undefined;
  /**
   * @member {Number} buyingOptionPayAmountCents
   */
  exports.prototype['buyingOptionPayAmountCents'] = undefined;



  return exports;
}));


