/**
 * Bottega
 * KSF Media's orders service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BuyingOption model module.
 * @module model/BuyingOption
 * @version 1.0.0
 */
class BuyingOption {
    /**
     * Constructs a new <code>BuyingOption</code>.
     * @alias module:model/BuyingOption
     * @param buyingOptionPackage {String} 
     * @param buyingOptionPeriod {Number} 
     * @param buyingOptionPayAmountCents {Number} 
     */
    constructor(buyingOptionPackage, buyingOptionPeriod, buyingOptionPayAmountCents) { 
        
        BuyingOption.initialize(this, buyingOptionPackage, buyingOptionPeriod, buyingOptionPayAmountCents);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, buyingOptionPackage, buyingOptionPeriod, buyingOptionPayAmountCents) { 
        obj['buyingOptionPackage'] = buyingOptionPackage;
        obj['buyingOptionPeriod'] = buyingOptionPeriod;
        obj['buyingOptionPayAmountCents'] = buyingOptionPayAmountCents;
    }

    /**
     * Constructs a <code>BuyingOption</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BuyingOption} obj Optional instance to populate.
     * @return {module:model/BuyingOption} The populated <code>BuyingOption</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BuyingOption();

            if (data.hasOwnProperty('buyingOptionPackage')) {
                obj['buyingOptionPackage'] = ApiClient.convertToType(data['buyingOptionPackage'], 'String');
            }
            if (data.hasOwnProperty('buyingOptionPeriod')) {
                obj['buyingOptionPeriod'] = ApiClient.convertToType(data['buyingOptionPeriod'], 'Number');
            }
            if (data.hasOwnProperty('buyingOptionPayAmountCents')) {
                obj['buyingOptionPayAmountCents'] = ApiClient.convertToType(data['buyingOptionPayAmountCents'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} buyingOptionPackage
 */
BuyingOption.prototype['buyingOptionPackage'] = undefined;

/**
 * @member {Number} buyingOptionPeriod
 */
BuyingOption.prototype['buyingOptionPeriod'] = undefined;

/**
 * @member {Number} buyingOptionPayAmountCents
 */
BuyingOption.prototype['buyingOptionPayAmountCents'] = undefined;






export default BuyingOption;

