/**
 * Bottega
 * KSF Media's orders service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Bottega) {
      root.Bottega = {};
    }
    root.Bottega.CreditCardRegisterStatus = factory(root.Bottega.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The CreditCardRegisterStatus model module.
   * @module model/CreditCardRegisterStatus
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CreditCardRegisterStatus</code>.
   * @alias module:model/CreditCardRegisterStatus
   * @class
   * @param state {String} 
   * @param time {String} 
   */
  var exports = function(state, time) {
    var _this = this;

    _this['state'] = state;
    _this['time'] = time;
  };

  /**
   * Constructs a <code>CreditCardRegisterStatus</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreditCardRegisterStatus} obj Optional instance to populate.
   * @return {module:model/CreditCardRegisterStatus} The populated <code>CreditCardRegisterStatus</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('state')) {
        obj['state'] = ApiClient.convertToType(data['state'], 'String');
      }
      if (data.hasOwnProperty('time')) {
        obj['time'] = ApiClient.convertToType(data['time'], 'String');
      }
      if (data.hasOwnProperty('failReason')) {
        obj['failReason'] = ApiClient.convertToType(data['failReason'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} state
   */
  exports.prototype['state'] = undefined;
  /**
   * @member {String} time
   */
  exports.prototype['time'] = undefined;
  /**
   * @member {String} failReason
   */
  exports.prototype['failReason'] = undefined;



  return exports;
}));


