/**
 * Bottega
 * KSF Media's orders service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Bottega) {
      root.Bottega = {};
    }
    root.Bottega.CreditCard = factory(root.Bottega.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The CreditCard model module.
   * @module model/CreditCard
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CreditCard</code>.
   * @alias module:model/CreditCard
   * @class
   * @param id {Number} 
   * @param user {String} 
   * @param paymentMethodId {Number} 
   * @param maskedPan {String} 
   * @param expiryDate {String} 
   */
  var exports = function(id, user, paymentMethodId, maskedPan, expiryDate) {
    var _this = this;

    _this['id'] = id;
    _this['user'] = user;
    _this['paymentMethodId'] = paymentMethodId;
    _this['maskedPan'] = maskedPan;
    _this['expiryDate'] = expiryDate;
  };

  /**
   * Constructs a <code>CreditCard</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreditCard} obj Optional instance to populate.
   * @return {module:model/CreditCard} The populated <code>CreditCard</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('user')) {
        obj['user'] = ApiClient.convertToType(data['user'], 'String');
      }
      if (data.hasOwnProperty('provider')) {
        obj['provider'] = ApiClient.convertToType(data['provider'], 'String');
      }
      if (data.hasOwnProperty('paymentMethodId')) {
        obj['paymentMethodId'] = ApiClient.convertToType(data['paymentMethodId'], 'Number');
      }
      if (data.hasOwnProperty('maskedPan')) {
        obj['maskedPan'] = ApiClient.convertToType(data['maskedPan'], 'String');
      }
      if (data.hasOwnProperty('expiryDate')) {
        obj['expiryDate'] = ApiClient.convertToType(data['expiryDate'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} user
   */
  exports.prototype['user'] = undefined;
  /**
   * @member {String} provider
   */
  exports.prototype['provider'] = undefined;
  /**
   * @member {Number} paymentMethodId
   */
  exports.prototype['paymentMethodId'] = undefined;
  /**
   * @member {String} maskedPan
   */
  exports.prototype['maskedPan'] = undefined;
  /**
   * @member {String} expiryDate
   */
  exports.prototype['expiryDate'] = undefined;



  return exports;
}));


