/**
 * Bottega
 * KSF Media's orders service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Bottega) {
      root.Bottega = {};
    }
    root.Bottega.ExternalOrderConfirmation = factory(root.Bottega.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The ExternalOrderConfirmation model module.
   * @module model/ExternalOrderConfirmation
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ExternalOrderConfirmation</code>.
   * @alias module:model/ExternalOrderConfirmation
   * @class
   * @param cusno {Number} 
   * @param email {String} 
   * @param name {String} 
   * @param lastname {String} 
   * @param firstname {String} 
   * @param subscriptionStart {String} 
   * @param subscriptionEnd {String} 
   * @param gift {String} 
   * @param paper {String} 
   * @param alias {String} 
   * @param subsno {Number} 
   * @param extno {String} 
   * @param productno {String} 
   */
  var exports = function(cusno, email, name, lastname, firstname, subscriptionStart, subscriptionEnd, gift, paper, alias, subsno, extno, productno) {
    var _this = this;

    _this['cusno'] = cusno;
    _this['email'] = email;
    _this['name'] = name;
    _this['lastname'] = lastname;
    _this['firstname'] = firstname;
    _this['subscription_start'] = subscriptionStart;
    _this['subscription_end'] = subscriptionEnd;
    _this['gift'] = gift;
    _this['paper'] = paper;
    _this['alias'] = alias;
    _this['subsno'] = subsno;
    _this['extno'] = extno;
    _this['productno'] = productno;
  };

  /**
   * Constructs a <code>ExternalOrderConfirmation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ExternalOrderConfirmation} obj Optional instance to populate.
   * @return {module:model/ExternalOrderConfirmation} The populated <code>ExternalOrderConfirmation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('cusno')) {
        obj['cusno'] = ApiClient.convertToType(data['cusno'], 'Number');
      }
      if (data.hasOwnProperty('email')) {
        obj['email'] = ApiClient.convertToType(data['email'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('lastname')) {
        obj['lastname'] = ApiClient.convertToType(data['lastname'], 'String');
      }
      if (data.hasOwnProperty('firstname')) {
        obj['firstname'] = ApiClient.convertToType(data['firstname'], 'String');
      }
      if (data.hasOwnProperty('subscription_start')) {
        obj['subscription_start'] = ApiClient.convertToType(data['subscription_start'], 'String');
      }
      if (data.hasOwnProperty('subscription_end')) {
        obj['subscription_end'] = ApiClient.convertToType(data['subscription_end'], 'String');
      }
      if (data.hasOwnProperty('gift')) {
        obj['gift'] = ApiClient.convertToType(data['gift'], 'String');
      }
      if (data.hasOwnProperty('paper')) {
        obj['paper'] = ApiClient.convertToType(data['paper'], 'String');
      }
      if (data.hasOwnProperty('alias')) {
        obj['alias'] = ApiClient.convertToType(data['alias'], 'String');
      }
      if (data.hasOwnProperty('subsno')) {
        obj['subsno'] = ApiClient.convertToType(data['subsno'], 'Number');
      }
      if (data.hasOwnProperty('extno')) {
        obj['extno'] = ApiClient.convertToType(data['extno'], 'String');
      }
      if (data.hasOwnProperty('productno')) {
        obj['productno'] = ApiClient.convertToType(data['productno'], 'String');
      }
      if (data.hasOwnProperty('productname')) {
        obj['productname'] = ApiClient.convertToType(data['productname'], 'String');
      }
      if (data.hasOwnProperty('price')) {
        obj['price'] = ApiClient.convertToType(data['price'], 'String');
      }
      if (data.hasOwnProperty('invmode')) {
        obj['invmode'] = ApiClient.convertToType(data['invmode'], 'String');
      }
      if (data.hasOwnProperty('campname')) {
        obj['campname'] = ApiClient.convertToType(data['campname'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} cusno
   */
  exports.prototype['cusno'] = undefined;
  /**
   * @member {String} email
   */
  exports.prototype['email'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} lastname
   */
  exports.prototype['lastname'] = undefined;
  /**
   * @member {String} firstname
   */
  exports.prototype['firstname'] = undefined;
  /**
   * @member {String} subscription_start
   */
  exports.prototype['subscription_start'] = undefined;
  /**
   * @member {String} subscription_end
   */
  exports.prototype['subscription_end'] = undefined;
  /**
   * @member {String} gift
   */
  exports.prototype['gift'] = undefined;
  /**
   * @member {String} paper
   */
  exports.prototype['paper'] = undefined;
  /**
   * @member {String} alias
   */
  exports.prototype['alias'] = undefined;
  /**
   * @member {Number} subsno
   */
  exports.prototype['subsno'] = undefined;
  /**
   * @member {String} extno
   */
  exports.prototype['extno'] = undefined;
  /**
   * @member {String} productno
   */
  exports.prototype['productno'] = undefined;
  /**
   * @member {String} productname
   */
  exports.prototype['productname'] = undefined;
  /**
   * @member {String} price
   */
  exports.prototype['price'] = undefined;
  /**
   * @member {String} invmode
   */
  exports.prototype['invmode'] = undefined;
  /**
   * @member {String} campname
   */
  exports.prototype['campname'] = undefined;



  return exports;
}));


