/**
 * Bottega
 * KSF Media's orders service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Bottega) {
      root.Bottega = {};
    }
    root.Bottega.Gift = factory(root.Bottega.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The Gift model module.
   * @module model/Gift
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Gift</code>.
   * @alias module:model/Gift
   * @class
   * @param owner {String} 
   * @param _package {String} 
   * @param used {Boolean} 
   */
  var exports = function(owner, _package, used) {
    var _this = this;

    _this['owner'] = owner;
    _this['package'] = _package;
    _this['used'] = used;
  };

  /**
   * Constructs a <code>Gift</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Gift} obj Optional instance to populate.
   * @return {module:model/Gift} The populated <code>Gift</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('owner')) {
        obj['owner'] = ApiClient.convertToType(data['owner'], 'String');
      }
      if (data.hasOwnProperty('package')) {
        obj['package'] = ApiClient.convertToType(data['package'], 'String');
      }
      if (data.hasOwnProperty('used')) {
        obj['used'] = ApiClient.convertToType(data['used'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {String} owner
   */
  exports.prototype['owner'] = undefined;
  /**
   * @member {String} package
   */
  exports.prototype['package'] = undefined;
  /**
   * @member {Boolean} used
   */
  exports.prototype['used'] = undefined;



  return exports;
}));


