/**
 * Bottega
 * KSF Media's orders service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Bottega) {
      root.Bottega = {};
    }
    root.Bottega.KayakWebhookEvent = factory(root.Bottega.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The KayakWebhookEvent model module.
   * @module model/KayakWebhookEvent
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>KayakWebhookEvent</code>.
   * @alias module:model/KayakWebhookEvent
   * @class
   * @param eventno {Number} 
   * @param eventtype {String} 
   * @param senttime {String} 
   */
  var exports = function(eventno, eventtype, senttime) {
    var _this = this;

    _this['eventno'] = eventno;
    _this['eventtype'] = eventtype;
    _this['senttime'] = senttime;
  };

  /**
   * Constructs a <code>KayakWebhookEvent</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/KayakWebhookEvent} obj Optional instance to populate.
   * @return {module:model/KayakWebhookEvent} The populated <code>KayakWebhookEvent</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('eventno')) {
        obj['eventno'] = ApiClient.convertToType(data['eventno'], 'Number');
      }
      if (data.hasOwnProperty('eventtype')) {
        obj['eventtype'] = ApiClient.convertToType(data['eventtype'], 'String');
      }
      if (data.hasOwnProperty('senttime')) {
        obj['senttime'] = ApiClient.convertToType(data['senttime'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} eventno
   */
  exports.prototype['eventno'] = undefined;
  /**
   * @member {String} eventtype
   */
  exports.prototype['eventtype'] = undefined;
  /**
   * @member {String} senttime
   */
  exports.prototype['senttime'] = undefined;



  return exports;
}));


