/**
 * Bottega
 * KSF Media's orders service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Bottega) {
      root.Bottega = {};
    }
    root.Bottega.KlarnaOrderProduct = factory(root.Bottega.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The KlarnaOrderProduct model module.
   * @module model/KlarnaOrderProduct
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>KlarnaOrderProduct</code>.
   * @alias module:model/KlarnaOrderProduct
   * @class
   * @param packageId {String} 
   * @param campaignNo {Number} 
   * @param countryCode {String} 
   */
  var exports = function(packageId, campaignNo, countryCode) {
    var _this = this;

    _this['packageId'] = packageId;
    _this['campaignNo'] = campaignNo;
    _this['countryCode'] = countryCode;
  };

  /**
   * Constructs a <code>KlarnaOrderProduct</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/KlarnaOrderProduct} obj Optional instance to populate.
   * @return {module:model/KlarnaOrderProduct} The populated <code>KlarnaOrderProduct</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('packageId')) {
        obj['packageId'] = ApiClient.convertToType(data['packageId'], 'String');
      }
      if (data.hasOwnProperty('campaignNo')) {
        obj['campaignNo'] = ApiClient.convertToType(data['campaignNo'], 'Number');
      }
      if (data.hasOwnProperty('countryCode')) {
        obj['countryCode'] = ApiClient.convertToType(data['countryCode'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} packageId
   */
  exports.prototype['packageId'] = undefined;
  /**
   * @member {Number} campaignNo
   */
  exports.prototype['campaignNo'] = undefined;
  /**
   * @member {String} countryCode
   */
  exports.prototype['countryCode'] = undefined;



  return exports;
}));


