/**
 * Bottega
 * KSF Media's orders service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Bottega) {
      root.Bottega = {};
    }
    root.Bottega.KlarnaInitResponse = factory(root.Bottega.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The KlarnaInitResponse model module.
   * @module model/KlarnaInitResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>KlarnaInitResponse</code>.
   * @alias module:model/KlarnaInitResponse
   * @class
   * @param campaignName {String} 
   * @param cost {Number} 
   * @param packageName {String} 
   * @param clientToken {String} 
   * @param intent {String} 
   */
  var exports = function(campaignName, cost, packageName, clientToken, intent) {
    var _this = this;

    _this['campaignName'] = campaignName;
    _this['cost'] = cost;
    _this['packageName'] = packageName;
    _this['clientToken'] = clientToken;
    _this['intent'] = intent;
  };

  /**
   * Constructs a <code>KlarnaInitResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/KlarnaInitResponse} obj Optional instance to populate.
   * @return {module:model/KlarnaInitResponse} The populated <code>KlarnaInitResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('campaignName')) {
        obj['campaignName'] = ApiClient.convertToType(data['campaignName'], 'String');
      }
      if (data.hasOwnProperty('cost')) {
        obj['cost'] = ApiClient.convertToType(data['cost'], 'Number');
      }
      if (data.hasOwnProperty('packageName')) {
        obj['packageName'] = ApiClient.convertToType(data['packageName'], 'String');
      }
      if (data.hasOwnProperty('clientToken')) {
        obj['clientToken'] = ApiClient.convertToType(data['clientToken'], 'String');
      }
      if (data.hasOwnProperty('intent')) {
        obj['intent'] = ApiClient.convertToType(data['intent'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} campaignName
   */
  exports.prototype['campaignName'] = undefined;
  /**
   * @member {Number} cost
   */
  exports.prototype['cost'] = undefined;
  /**
   * @member {String} packageName
   */
  exports.prototype['packageName'] = undefined;
  /**
   * @member {String} clientToken
   */
  exports.prototype['clientToken'] = undefined;
  /**
   * @member {String} intent
   */
  exports.prototype['intent'] = undefined;



  return exports;
}));


