/**
 * Bottega
 * KSF Media's orders service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Bottega) {
      root.Bottega = {};
    }
    root.Bottega.OrderErrorReason = factory(root.Bottega.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';


  /**
   * Enum class OrderErrorReason.
   * @enum {}
   * @readonly
   */
  var exports = {
    /**
     * value: "NetsInternalError"
     * @const
     */
    "NetsInternalError": "NetsInternalError",
    /**
     * value: "NetsIssuerError"
     * @const
     */
    "NetsIssuerError": "NetsIssuerError",
    /**
     * value: "SubscriptionExistsError"
     * @const
     */
    "SubscriptionExistsError": "SubscriptionExistsError",
    /**
     * value: "SubscriptionError"
     * @const
     */
    "SubscriptionError": "SubscriptionError",
    /**
     * value: "OrderNotFound"
     * @const
     */
    "OrderNotFound": "OrderNotFound"  };

  /**
   * Returns a <code>OrderErrorReason</code> enum value from a Javascript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/OrderErrorReason} The enum <code>OrderErrorReason</code> value.
   */
  exports.constructFromObject = function(object) {
    return object;
  }

  return exports;
}));


