/**
 * Bottega
 * KSF Media's orders service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OrderStatus model module.
 * @module model/OrderStatus
 * @version 1.0.0
 */
class OrderStatus {
    /**
     * Constructs a new <code>OrderStatus</code>.
     * @alias module:model/OrderStatus
     */
    constructor() { 
        
        OrderStatus.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OrderStatus</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OrderStatus} obj Optional instance to populate.
     * @return {module:model/OrderStatus} The populated <code>OrderStatus</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrderStatus();

            if (data.hasOwnProperty('OrderCreated')) {
                obj['OrderCreated'] = ApiClient.convertToType(data['OrderCreated'], 'String');
            }
            if (data.hasOwnProperty('OrderStarted')) {
                obj['OrderStarted'] = ApiClient.convertToType(data['OrderStarted'], 'String');
            }
            if (data.hasOwnProperty('OrderCompleted')) {
                obj['OrderCompleted'] = ApiClient.convertToType(data['OrderCompleted'], 'String');
            }
            if (data.hasOwnProperty('OrderFailed')) {
                obj['OrderFailed'] = ApiClient.convertToType(data['OrderFailed'], [Object]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} OrderCreated
 */
OrderStatus.prototype['OrderCreated'] = undefined;

/**
 * @member {String} OrderStarted
 */
OrderStatus.prototype['OrderStarted'] = undefined;

/**
 * @member {String} OrderCompleted
 */
OrderStatus.prototype['OrderCompleted'] = undefined;

/**
 * @member {Array.<Object>} OrderFailed
 */
OrderStatus.prototype['OrderFailed'] = undefined;






export default OrderStatus;

