/**
 * Bottega
 * KSF Media's orders service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Bottega) {
      root.Bottega = {};
    }
    root.Bottega.OrderStatus = factory(root.Bottega.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The OrderStatus model module.
   * @module model/OrderStatus
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>OrderStatus</code>.
   * @alias module:model/OrderStatus
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>OrderStatus</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderStatus} obj Optional instance to populate.
   * @return {module:model/OrderStatus} The populated <code>OrderStatus</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('OrderCreated')) {
        obj['OrderCreated'] = ApiClient.convertToType(data['OrderCreated'], 'String');
      }
      if (data.hasOwnProperty('OrderStarted')) {
        obj['OrderStarted'] = ApiClient.convertToType(data['OrderStarted'], 'String');
      }
      if (data.hasOwnProperty('OrderCompleted')) {
        obj['OrderCompleted'] = ApiClient.convertToType(data['OrderCompleted'], 'String');
      }
      if (data.hasOwnProperty('OrderFailed')) {
        obj['OrderFailed'] = ApiClient.convertToType(data['OrderFailed'], [Object]);
      }
    }
    return obj;
  }

  /**
   * @member {String} OrderCreated
   */
  exports.prototype['OrderCreated'] = undefined;
  /**
   * @member {String} OrderStarted
   */
  exports.prototype['OrderStarted'] = undefined;
  /**
   * @member {String} OrderCompleted
   */
  exports.prototype['OrderCompleted'] = undefined;
  /**
   * @member {Array.<Object>} OrderFailed
   */
  exports.prototype['OrderFailed'] = undefined;



  return exports;
}));


