/**
 * Bottega
 * KSF Media's orders service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/OrderStatus'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./OrderStatus'));
  } else {
    // Browser globals (root is window)
    if (!root.Bottega) {
      root.Bottega = {};
    }
    root.Bottega.Order = factory(root.Bottega.ApiClient, root.Bottega.OrderStatus);
  }
}(this, function(ApiClient, OrderStatus) {
  'use strict';



  /**
   * The Order model module.
   * @module model/Order
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Order</code>.
   * @alias module:model/Order
   * @class
   * @param orderNumber {String} 
   * @param orderUser {String} 
   * @param orderStatus {module:model/OrderStatus} 
   */
  var exports = function(orderNumber, orderUser, orderStatus) {
    var _this = this;

    _this['orderNumber'] = orderNumber;
    _this['orderUser'] = orderUser;
    _this['orderStatus'] = orderStatus;
  };

  /**
   * Constructs a <code>Order</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Order} obj Optional instance to populate.
   * @return {module:model/Order} The populated <code>Order</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('orderNumber')) {
        obj['orderNumber'] = ApiClient.convertToType(data['orderNumber'], 'String');
      }
      if (data.hasOwnProperty('orderUser')) {
        obj['orderUser'] = ApiClient.convertToType(data['orderUser'], 'String');
      }
      if (data.hasOwnProperty('orderStatus')) {
        obj['orderStatus'] = OrderStatus.constructFromObject(data['orderStatus']);
      }
    }
    return obj;
  }

  /**
   * @member {String} orderNumber
   */
  exports.prototype['orderNumber'] = undefined;
  /**
   * @member {String} orderUser
   */
  exports.prototype['orderUser'] = undefined;
  /**
   * @member {module:model/OrderStatus} orderStatus
   */
  exports.prototype['orderStatus'] = undefined;



  return exports;
}));


