/**
 * Bottega
 * KSF Media's orders service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class OrderErrorReason.
* @enum {}
* @readonly
*/
export default class OrderErrorReason {
    
        /**
         * value: "NetsInternalError"
         * @const
         */
        "NetsInternalError" = "NetsInternalError";

    
        /**
         * value: "NetsIssuerError"
         * @const
         */
        "NetsIssuerError" = "NetsIssuerError";

    
        /**
         * value: "SubscriptionExistsError"
         * @const
         */
        "SubscriptionExistsError" = "SubscriptionExistsError";

    
        /**
         * value: "SubscriptionError"
         * @const
         */
        "SubscriptionError" = "SubscriptionError";

    
        /**
         * value: "OrderNotFound"
         * @const
         */
        "OrderNotFound" = "OrderNotFound";

    

    /**
    * Returns a <code>OrderErrorReason</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/OrderErrorReason} The enum <code>OrderErrorReason</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

