/**
 * Bottega
 * KSF Media's orders service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OrderStatus from './OrderStatus';

/**
 * The Order model module.
 * @module model/Order
 * @version 1.0.0
 */
class Order {
    /**
     * Constructs a new <code>Order</code>.
     * @alias module:model/Order
     * @param orderNumber {String} 
     * @param orderUser {String} 
     * @param orderStatus {module:model/OrderStatus} 
     */
    constructor(orderNumber, orderUser, orderStatus) { 
        
        Order.initialize(this, orderNumber, orderUser, orderStatus);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, orderNumber, orderUser, orderStatus) { 
        obj['orderNumber'] = orderNumber;
        obj['orderUser'] = orderUser;
        obj['orderStatus'] = orderStatus;
    }

    /**
     * Constructs a <code>Order</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Order} obj Optional instance to populate.
     * @return {module:model/Order} The populated <code>Order</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Order();

            if (data.hasOwnProperty('orderNumber')) {
                obj['orderNumber'] = ApiClient.convertToType(data['orderNumber'], 'String');
            }
            if (data.hasOwnProperty('orderUser')) {
                obj['orderUser'] = ApiClient.convertToType(data['orderUser'], 'String');
            }
            if (data.hasOwnProperty('orderStatus')) {
                obj['orderStatus'] = OrderStatus.constructFromObject(data['orderStatus']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} orderNumber
 */
Order.prototype['orderNumber'] = undefined;

/**
 * @member {String} orderUser
 */
Order.prototype['orderUser'] = undefined;

/**
 * @member {module:model/OrderStatus} orderStatus
 */
Order.prototype['orderStatus'] = undefined;






export default Order;

