/**
 * Bottega
 * KSF Media's orders service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class PaymentOption.
* @enum {}
* @readonly
*/
export default class PaymentOption {
    
        /**
         * value: "Bill"
         * @const
         */
        "Bill" = "Bill";

    
        /**
         * value: "CreditCard"
         * @const
         */
        "CreditCard" = "CreditCard";

    
        /**
         * value: "BankPayment"
         * @const
         */
        "BankPayment" = "BankPayment";

    

    /**
    * Returns a <code>PaymentOption</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/PaymentOption} The enum <code>PaymentOption</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

