/**
 * Bottega
 * KSF Media's orders service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Bottega) {
      root.Bottega = {};
    }
    root.Bottega.PaymentTerminalUrl = factory(root.Bottega.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The PaymentTerminalUrl model module.
   * @module model/PaymentTerminalUrl
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PaymentTerminalUrl</code>.
   * @alias module:model/PaymentTerminalUrl
   * @class
   * @param paymentTerminalUrl {String} 
   */
  var exports = function(paymentTerminalUrl) {
    var _this = this;

    _this['paymentTerminalUrl'] = paymentTerminalUrl;
  };

  /**
   * Constructs a <code>PaymentTerminalUrl</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PaymentTerminalUrl} obj Optional instance to populate.
   * @return {module:model/PaymentTerminalUrl} The populated <code>PaymentTerminalUrl</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('paymentTerminalUrl')) {
        obj['paymentTerminalUrl'] = ApiClient.convertToType(data['paymentTerminalUrl'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} paymentTerminalUrl
   */
  exports.prototype['paymentTerminalUrl'] = undefined;



  return exports;
}));


