/**
 * Bottega
 * KSF Media's orders service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Gift', 'model/InlineResponse400', 'model/InlineResponse415', 'model/KlarnaInitResponse', 'model/KlarnaOrderProduct', 'model/Order', 'model/OrderProduct', 'model/PayOrderRequest', 'model/PaymentTerminalUrl'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Gift'), require('../model/InlineResponse400'), require('../model/InlineResponse415'), require('../model/KlarnaInitResponse'), require('../model/KlarnaOrderProduct'), require('../model/Order'), require('../model/OrderProduct'), require('../model/PayOrderRequest'), require('../model/PaymentTerminalUrl'));
  } else {
    // Browser globals (root is window)
    if (!root.Bottega) {
      root.Bottega = {};
    }
    root.Bottega.OrdersApi = factory(root.Bottega.ApiClient, root.Bottega.Gift, root.Bottega.InlineResponse400, root.Bottega.InlineResponse415, root.Bottega.KlarnaInitResponse, root.Bottega.KlarnaOrderProduct, root.Bottega.Order, root.Bottega.OrderProduct, root.Bottega.PayOrderRequest, root.Bottega.PaymentTerminalUrl);
  }
}(this, function(ApiClient, Gift, InlineResponse400, InlineResponse415, KlarnaInitResponse, KlarnaOrderProduct, Order, OrderProduct, PayOrderRequest, PaymentTerminalUrl) {
  'use strict';

  /**
   * Orders service.
   * @module api/OrdersApi
   * @version 1.0.0
   */

  /**
   * Constructs a new OrdersApi. 
   * @alias module:api/OrdersApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the orderCallbackPost operation.
     * @callback module:api/OrdersApi~orderCallbackPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Handles Nets server side transaction callback
     * @param {String} authorization 
     * @param {String} body 
     * @param {module:api/OrdersApi~orderCallbackPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.orderCallbackPost = function(authorization, body, callback) {
      var postBody = body;
      // verify the required parameter 'authorization' is set
      if (authorization === undefined || authorization === null) {
        throw new Error("Missing the required parameter 'authorization' when calling orderCallbackPost");
      }
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling orderCallbackPost");
      }

      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'Authorization': authorization
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json;charset=utf-8'];
      var accepts = [];
      var returnType = null;
      return this.apiClient.callApi(
        '/order/callback', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the orderGiftGiftCodeGet operation.
     * @callback module:api/OrdersApi~orderGiftGiftCodeGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Gift} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Query a gift code
     * @param {String} giftCode 
     * @param {module:api/OrdersApi~orderGiftGiftCodeGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Gift}
     */
    this.orderGiftGiftCodeGet = function(giftCode, callback) {
      var postBody = null;
      // verify the required parameter 'giftCode' is set
      if (giftCode === undefined || giftCode === null) {
        throw new Error("Missing the required parameter 'giftCode' when calling orderGiftGiftCodeGet");
      }

      var pathParams = {
        'giftCode': giftCode
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json;charset=utf-8'];
      var returnType = Gift;
      return this.apiClient.callApi(
        '/order/gift/{giftCode}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the orderGiftGiftCodePut operation.
     * @callback module:api/OrdersApi~orderGiftGiftCodePutCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Redeem a gift code to get subscription
     * @param {String} giftCode 
     * @param {Object} opts Optional parameters
     * @param {String} opts.authUser 
     * @param {String} opts.authorization 
     * @param {module:api/OrdersApi~orderGiftGiftCodePutCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.orderGiftGiftCodePut = function(giftCode, opts, callback) {
      opts = opts || {};
      var postBody = null;
      // verify the required parameter 'giftCode' is set
      if (giftCode === undefined || giftCode === null) {
        throw new Error("Missing the required parameter 'giftCode' when calling orderGiftGiftCodePut");
      }

      var pathParams = {
        'giftCode': giftCode
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'AuthUser': opts['authUser'],
        'Authorization': opts['authorization']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;
      return this.apiClient.callApi(
        '/order/gift/{giftCode}', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the orderInitKlarnaPost operation.
     * @callback module:api/OrdersApi~orderInitKlarnaPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/KlarnaInitResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Initialize a Klarna payment
     * @param {module:model/KlarnaOrderProduct} body 
     * @param {module:api/OrdersApi~orderInitKlarnaPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/KlarnaInitResponse}
     */
    this.orderInitKlarnaPost = function(body, callback) {
      var postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling orderInitKlarnaPost");
      }

      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json;charset=utf-8'];
      var accepts = ['application/json;charset=utf-8'];
      var returnType = KlarnaInitResponse;
      return this.apiClient.callApi(
        '/order/initKlarna', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the orderOrderNumberGet operation.
     * @callback module:api/OrdersApi~orderOrderNumberGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Order} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Fetch order by UUID
     * @param {String} orderNumber 
     * @param {Object} opts Optional parameters
     * @param {String} opts.authUser 
     * @param {String} opts.authorization 
     * @param {module:api/OrdersApi~orderOrderNumberGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Order}
     */
    this.orderOrderNumberGet = function(orderNumber, opts, callback) {
      opts = opts || {};
      var postBody = null;
      // verify the required parameter 'orderNumber' is set
      if (orderNumber === undefined || orderNumber === null) {
        throw new Error("Missing the required parameter 'orderNumber' when calling orderOrderNumberGet");
      }

      var pathParams = {
        'orderNumber': orderNumber
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'AuthUser': opts['authUser'],
        'Authorization': opts['authorization']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json;charset=utf-8'];
      var returnType = Order;
      return this.apiClient.callApi(
        '/order/{orderNumber}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the orderOrderNumberPayPost operation.
     * @callback module:api/OrdersApi~orderOrderNumberPayPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PaymentTerminalUrl} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Pay for an Order, marking it as ready for processing
     * @param {String} orderNumber 
     * @param {module:model/PayOrderRequest} body 
     * @param {Object} opts Optional parameters
     * @param {String} opts.authUser 
     * @param {String} opts.authorization 
     * @param {module:api/OrdersApi~orderOrderNumberPayPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PaymentTerminalUrl}
     */
    this.orderOrderNumberPayPost = function(orderNumber, body, opts, callback) {
      opts = opts || {};
      var postBody = body;
      // verify the required parameter 'orderNumber' is set
      if (orderNumber === undefined || orderNumber === null) {
        throw new Error("Missing the required parameter 'orderNumber' when calling orderOrderNumberPayPost");
      }
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling orderOrderNumberPayPost");
      }

      var pathParams = {
        'orderNumber': orderNumber
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'AuthUser': opts['authUser'],
        'Authorization': opts['authorization']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json;charset=utf-8'];
      var accepts = ['application/json;charset=utf-8'];
      var returnType = PaymentTerminalUrl;
      return this.apiClient.callApi(
        '/order/{orderNumber}/pay', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the orderPost operation.
     * @callback module:api/OrdersApi~orderPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Order} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a new Order
     * @param {module:model/OrderProduct} body 
     * @param {Object} opts Optional parameters
     * @param {String} opts.authUser 
     * @param {String} opts.authorization 
     * @param {module:api/OrdersApi~orderPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Order}
     */
    this.orderPost = function(body, opts, callback) {
      opts = opts || {};
      var postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling orderPost");
      }

      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'AuthUser': opts['authUser'],
        'Authorization': opts['authorization']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json;charset=utf-8'];
      var accepts = ['application/json;charset=utf-8'];
      var returnType = Order;
      return this.apiClient.callApi(
        '/order', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the orderProcessOrderGet operation.
     * @callback module:api/OrdersApi~orderProcessOrderGetCallback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Handles Nets payment response
     * @param {Object} opts Optional parameters
     * @param {String} opts.transactionId 
     * @param {String} opts.responseCode 
     * @param {module:api/OrdersApi~orderProcessOrderGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    this.orderProcessOrderGet = function(opts, callback) {
      opts = opts || {};
      var postBody = null;

      var pathParams = {
      };
      var queryParams = {
        'transactionId': opts['transactionId'],
        'responseCode': opts['responseCode'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['text/html;charset=utf-8'];
      var returnType = 'String';
      return this.apiClient.callApi(
        '/order/processOrder', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }
  };

  return exports;
}));
