/**
 * Bottega
 * KSF Media's orders service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Bottega);
  }
}(this, function(expect, Bottega) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Bottega.ExternalOrderConfirmation();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ExternalOrderConfirmation', function() {
    it('should create an instance of ExternalOrderConfirmation', function() {
      // uncomment below and update the code to test ExternalOrderConfirmation
      //var instance = new Bottega.ExternalOrderConfirmation();
      //expect(instance).to.be.a(Bottega.ExternalOrderConfirmation);
    });

    it('should have the property cusno (base name: "cusno")', function() {
      // uncomment below and update the code to test the property cusno
      //var instance = new Bottega.ExternalOrderConfirmation();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new Bottega.ExternalOrderConfirmation();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new Bottega.ExternalOrderConfirmation();
      //expect(instance).to.be();
    });

    it('should have the property lastname (base name: "lastname")', function() {
      // uncomment below and update the code to test the property lastname
      //var instance = new Bottega.ExternalOrderConfirmation();
      //expect(instance).to.be();
    });

    it('should have the property firstname (base name: "firstname")', function() {
      // uncomment below and update the code to test the property firstname
      //var instance = new Bottega.ExternalOrderConfirmation();
      //expect(instance).to.be();
    });

    it('should have the property subscriptionStart (base name: "subscription_start")', function() {
      // uncomment below and update the code to test the property subscriptionStart
      //var instance = new Bottega.ExternalOrderConfirmation();
      //expect(instance).to.be();
    });

    it('should have the property subscriptionEnd (base name: "subscription_end")', function() {
      // uncomment below and update the code to test the property subscriptionEnd
      //var instance = new Bottega.ExternalOrderConfirmation();
      //expect(instance).to.be();
    });

    it('should have the property gift (base name: "gift")', function() {
      // uncomment below and update the code to test the property gift
      //var instance = new Bottega.ExternalOrderConfirmation();
      //expect(instance).to.be();
    });

    it('should have the property paper (base name: "paper")', function() {
      // uncomment below and update the code to test the property paper
      //var instance = new Bottega.ExternalOrderConfirmation();
      //expect(instance).to.be();
    });

    it('should have the property alias (base name: "alias")', function() {
      // uncomment below and update the code to test the property alias
      //var instance = new Bottega.ExternalOrderConfirmation();
      //expect(instance).to.be();
    });

    it('should have the property subsno (base name: "subsno")', function() {
      // uncomment below and update the code to test the property subsno
      //var instance = new Bottega.ExternalOrderConfirmation();
      //expect(instance).to.be();
    });

    it('should have the property extno (base name: "extno")', function() {
      // uncomment below and update the code to test the property extno
      //var instance = new Bottega.ExternalOrderConfirmation();
      //expect(instance).to.be();
    });

    it('should have the property productno (base name: "productno")', function() {
      // uncomment below and update the code to test the property productno
      //var instance = new Bottega.ExternalOrderConfirmation();
      //expect(instance).to.be();
    });

  });

}));
