/**
 * Bottega
 * KSF Media's orders service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BuyingOption', 'model/InlineResponse400', 'model/InlineResponse400InvalidRequestBody', 'model/InlineResponse415', 'model/InlineResponse415UnsupportedMediaType', 'model/Order', 'model/OrderErrorReason', 'model/OrderStatus', 'model/PaymentOption', 'model/PaymentTerminalUrl', 'api/OrdersApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/BuyingOption'), require('./model/InlineResponse400'), require('./model/InlineResponse400InvalidRequestBody'), require('./model/InlineResponse415'), require('./model/InlineResponse415UnsupportedMediaType'), require('./model/Order'), require('./model/OrderErrorReason'), require('./model/OrderStatus'), require('./model/PaymentOption'), require('./model/PaymentTerminalUrl'), require('./api/OrdersApi'));
  }
}(function(ApiClient, BuyingOption, InlineResponse400, InlineResponse400InvalidRequestBody, InlineResponse415, InlineResponse415UnsupportedMediaType, Order, OrderErrorReason, OrderStatus, PaymentOption, PaymentTerminalUrl, OrdersApi) {
  'use strict';

  /**
   * KSF_Medias_orders_service.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var Bottega = require('index'); // See note below*.
   * var xxxSvc = new Bottega.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new Bottega.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new Bottega.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new Bottega.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The BuyingOption model constructor.
     * @property {module:model/BuyingOption}
     */
    BuyingOption: BuyingOption,
    /**
     * The InlineResponse400 model constructor.
     * @property {module:model/InlineResponse400}
     */
    InlineResponse400: InlineResponse400,
    /**
     * The InlineResponse400InvalidRequestBody model constructor.
     * @property {module:model/InlineResponse400InvalidRequestBody}
     */
    InlineResponse400InvalidRequestBody: InlineResponse400InvalidRequestBody,
    /**
     * The InlineResponse415 model constructor.
     * @property {module:model/InlineResponse415}
     */
    InlineResponse415: InlineResponse415,
    /**
     * The InlineResponse415UnsupportedMediaType model constructor.
     * @property {module:model/InlineResponse415UnsupportedMediaType}
     */
    InlineResponse415UnsupportedMediaType: InlineResponse415UnsupportedMediaType,
    /**
     * The Order model constructor.
     * @property {module:model/Order}
     */
    Order: Order,
    /**
     * The OrderErrorReason model constructor.
     * @property {module:model/OrderErrorReason}
     */
    OrderErrorReason: OrderErrorReason,
    /**
     * The OrderStatus model constructor.
     * @property {module:model/OrderStatus}
     */
    OrderStatus: OrderStatus,
    /**
     * The PaymentOption model constructor.
     * @property {module:model/PaymentOption}
     */
    PaymentOption: PaymentOption,
    /**
     * The PaymentTerminalUrl model constructor.
     * @property {module:model/PaymentTerminalUrl}
     */
    PaymentTerminalUrl: PaymentTerminalUrl,
    /**
     * The OrdersApi service constructor.
     * @property {module:api/OrdersApi}
     */
    OrdersApi: OrdersApi
  };

  return exports;
}));
