/**
 * Bottega
 * KSF Media's orders service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import BuyingOption from './model/BuyingOption';
import InlineResponse400 from './model/InlineResponse400';
import InlineResponse400InvalidRequestBody from './model/InlineResponse400InvalidRequestBody';
import InlineResponse415 from './model/InlineResponse415';
import InlineResponse415UnsupportedMediaType from './model/InlineResponse415UnsupportedMediaType';
import Order from './model/Order';
import OrderErrorReason from './model/OrderErrorReason';
import OrderStatus from './model/OrderStatus';
import PaymentOption from './model/PaymentOption';
import OrdersApi from './api/OrdersApi';


/**
* KSF_Medias_orders_service.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var Bottega = require('index'); // See note below*.
* var xxxSvc = new Bottega.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new Bottega.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new Bottega.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new Bottega.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The BuyingOption model constructor.
     * @property {module:model/BuyingOption}
     */
    BuyingOption,

    /**
     * The InlineResponse400 model constructor.
     * @property {module:model/InlineResponse400}
     */
    InlineResponse400,

    /**
     * The InlineResponse400InvalidRequestBody model constructor.
     * @property {module:model/InlineResponse400InvalidRequestBody}
     */
    InlineResponse400InvalidRequestBody,

    /**
     * The InlineResponse415 model constructor.
     * @property {module:model/InlineResponse415}
     */
    InlineResponse415,

    /**
     * The InlineResponse415UnsupportedMediaType model constructor.
     * @property {module:model/InlineResponse415UnsupportedMediaType}
     */
    InlineResponse415UnsupportedMediaType,

    /**
     * The Order model constructor.
     * @property {module:model/Order}
     */
    Order,

    /**
     * The OrderErrorReason model constructor.
     * @property {module:model/OrderErrorReason}
     */
    OrderErrorReason,

    /**
     * The OrderStatus model constructor.
     * @property {module:model/OrderStatus}
     */
    OrderStatus,

    /**
     * The PaymentOption model constructor.
     * @property {module:model/PaymentOption}
     */
    PaymentOption,

    /**
    * The OrdersApi service constructor.
    * @property {module:api/OrdersApi}
    */
    OrdersApi
};
