/**
 * Bottega
 * KSF Media's orders service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Bottega);
  }
}(this, function(expect, Bottega) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Bottega.OrdersApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OrdersApi', function() {
    describe('orderCallbackPost', function() {
      it('should call orderCallbackPost successfully', function(done) {
        //uncomment below and update the code to test orderCallbackPost
        //instance.orderCallbackPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('orderConfirmationPost', function() {
      it('should call orderConfirmationPost successfully', function(done) {
        //uncomment below and update the code to test orderConfirmationPost
        //instance.orderConfirmationPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('orderOrderNumberGet', function() {
      it('should call orderOrderNumberGet successfully', function(done) {
        //uncomment below and update the code to test orderOrderNumberGet
        //instance.orderOrderNumberGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('orderOrderNumberPayPost', function() {
      it('should call orderOrderNumberPayPost successfully', function(done) {
        //uncomment below and update the code to test orderOrderNumberPayPost
        //instance.orderOrderNumberPayPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('orderPost', function() {
      it('should call orderPost successfully', function(done) {
        //uncomment below and update the code to test orderPost
        //instance.orderPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('orderProcessOrderGet', function() {
      it('should call orderProcessOrderGet successfully', function(done) {
        //uncomment below and update the code to test orderProcessOrderGet
        //instance.orderProcessOrderGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
